### ISSUE TITLE
Crash when picking up Bottle o' Enchanting (due to it being non-alphabetic)

### ISSUE THREAD

**Issue by ShaneTRS** [Gibatron/letters#1]
Replacing all instances of `toLowerCase().replace(" ", "")` to `toLowerCase().replaceAll("[^a-z]", "").replaceAll(" ", "")` locally seems to have done the trick. Though, there are definitely better ways of fixing this bug.

**Comment by noWickedfortheRest** [comment]
Just released version 1.2.0 that fixes this, solved it by replacing the letters.get methods with a safer letters.getOrDefault method. Thanks for reporting it.
